# Define 'Service' to expose FrontEnd Application
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector: # pod labels should match these
    app: app-frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort # use NodePort if you are not running Kubernetes on Cloud
---
# 'Deployment' to manage of configuration of frontEnd Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels: # pod labels should match these
    app: app-frontend
    tier: frontend
spec:
  replicas: 2  # number of replicas of frontEnd application
  selector:
    matchLabels: 
      app: app-frontend
      tier: frontend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: app-frontend
        tier: frontend  
    spec:                 
      containers: 
      - name: frontend
        image: abirhsaini/frontend:tagname # docker image of frontend application
        env: # Setting Environmental Variables
          -  name: SERVER_URI # Setting Backend URI from configMap
             valueFrom:
               configMapKeyRef:
                 name: backend-conf # Name of configMap
                 key: server-uri
        ports:
        - containerPort: 80
  